import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  //Autogenerated sidebar: DISABLED
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  //Manual defined sidebar: ALLOWED
  apiGuideSidebar: [
      {
          type: 'category',
          label: 'API Guide',
          items: [
              {
                  type:     'doc',
                  label:    'Intro',
                  id:       'api-guide/api-guide-intro'
              },
              {
                  type:     'category',
                  label:    'Common objects',
                  items: [
                            'api-guide/objects-common/match-clock',
                            'api-guide/objects-common/time-frame'
                  ],
              },
              {
                  type:     'category',
                  label:    'Business objects',
                  items: [
                            'api-guide/objects-business/competition',
                            'api-guide/objects-business/season',
                            'api-guide/objects-business/season-stage',
                              //Object Match has child objects
                              {
                                  type:  'category',
                                  label: 'Match',
                                  items: [
                                      'api-guide/objects-business/match/match',
                                      'api-guide/objects-business/match/lineup',
                                      'api-guide/objects-business/match/match-events',
                                      'api-guide/objects-business/match/match-momentum',
                                      'api-guide/objects-business/match/player-rating'
                                  ],
                              },
                            'api-guide/objects-business/player',
                            'api-guide/objects-business/team',
                            //Object Stats has child objects
                              {
                                  type:  'category',
                                  label: 'Stats',
                                  items: [
                                      'api-guide/objects-business/stats/stats',
                                      'api-guide/objects-business/stats/stats-team-match',
                                      'api-guide/objects-business/stats/stats-player-match',
                                      'api-guide/objects-business/stats/stats-team-aggregated',
                                      'api-guide/objects-business/stats/stats-player-aggregated',
                                  ],
                              },

                  ],
              },
          ],
      },
  ],
  apiReferenceSidebar: [
    {
        type: 'category',
        label: 'API Reference',
        items: [
            {
                type: 'autogenerated',
                dirName: 'api-reference',
            },
        ],
    },
  ]
  /*apiReferenceSidebar: [
      {
          type: 'category',
          label: 'API Reference',
          items: [
              // INTO
              {
                  type:     'doc',
                  label:    'Intro',
                  id:       'api-reference/apiReferenceIntro'
              },
              // OBJECTS
              {
                  type: 'category',
                  label: 'Objects',
                  collapsed: false,
                  items: [{ type: 'autogenerated', dirName: 'api-reference/objects' }],
              },
              // ENUMS
              {
                  type: 'category',
                  label: 'Enums',
                  items: [{ type: 'autogenerated', dirName: 'api-reference/enums' }],
              },
              // INTERFACES
              {
                  type: 'category',
                  label: 'Interfaces',
                  items: [{ type: 'autogenerated', dirName: 'api-reference/interfaces' }],
              },
              // INPUTS
              {
                  type: 'category',
                  label: 'Inputs',
                  items: [{ type: 'autogenerated', dirName: 'api-reference/inputs' }],
              },
              // SCALARS
              {
                  type: 'category',
                  label: 'Scalars',
                  items: [{ type: 'autogenerated', dirName: 'api-reference/scalars' }],
              },

          ],
      },
  ]*/
  //objectSidebar: [{type: 'autogenerated', dirName: 'objects'}],
  //enumsSidebar:  [{type: 'autogenerated', dirName: 'enums'}],
  //inputsSidebar: [{type: 'autogenerated', dirName: 'inputs'}]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
